version: 2.1

jobs:
  build:
    docker:
      - image: python:3.10-slim
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-venv-{{ checksum "Pipfile.lock" }}
            - v1-venv-
      - run:
          name: install dependencies
          command: |
            pip install --upgrade pipenv
            pipenv sync --dev
            pipenv run pip install bandit
      - save_cache:
          paths:
            - /root/.cache/pip
            - ./.venv
          key: v1-venv-{{ checksum "Pipfile.lock" }}
      - run:
          name: run tests
          command: |
            pipenv run python -m unittest discover
      - run:
          name: run bandit
          command: |
            bandit -r /root/plex-stuff/server_code.py

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:XyQ+4w8reTjwDTLRpVLnf+RGOO/EwVZjq+OTastskKU"
      - run:
          name: Deploy to DigitalOcean
          command: |
            ssh -o StrictHostKeyChecking=no root@206.81.16.199 \<<- 'ENDSSH'
              set -e
              echo "Pulling latest code from repository..."
              cd ~/plex-stuff
              git pull
              if [ $? -ne 0 ]; then
                echo "Error pulling latest code."
                exit 1
              fi
              echo "Reloading systemd daemon to update service definitions..."
              sudo systemctl daemon-reload
              if [ $? -ne 0 ]; then
                echo "Error reloading systemd daemon."
                exit 1
              fi
              echo "Restarting pybackend service..."
              sudo systemctl restart pybackend.service
              if [ $? -ne 0 ]; then
                echo "Error restarting pybackend service."
                exit 1
              fi
              echo "Deployment successful and application restarted!"
            ENDSSH

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
